server:
  port: 8082

spring:
  config:

    import: optional:file:.env[.properties]

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ai-worker-group-v3
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  ai:
    google:
      genai:
        api-key: ${GEMINI_API_KEY}
        chat:
          options:
            model: gemini-2.5-flash


  datasource:
    url: jdbc:postgresql://localhost:5432/sentiment_db
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

app:
  finnhub:
    base-url: https://finnhub.io/api/v1
    api-key: ${FINNHUB_API_KEY}